repos:
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
    - id: black-jupyter
      types_or: ["python","jupyter"] 
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
- repo: https://github.com/PyCQA/autoflake
  rev: v2.0.2
  hooks:
    - id: autoflake
- repo: https://github.com/nbQA-dev/nbQA # for jupyter notebooks
  rev: 1.3.1
  hooks:
    - id: nbqa-isort 
    # Note: autoflake is not supported https://github.com/nbQA-dev/nbQA/issues/755
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 1.1.0
  hooks:
    - id: sync_with_poetry
      args: [
          '--all',  # Scan all dependencies in poetry.lock (main and dev)
      ]
