repos:
- repo: https://github.com/psf/black
  rev: 25.1.0  # NOTE: If updating, also update the version in .github/workflows/*
  hooks:
    - id: black-jupyter
      types_or: ["python","jupyter"] 
- repo: https://github.com/pycqa/isort
  rev: 5.12.0  # NOTE: If updating, also update the version in .github/workflows/*
  hooks:
    - id: isort
- repo: https://github.com/PyCQA/autoflake
  rev: v2.0.2
  hooks:
    - id: autoflake
      args: [--remove-all-unused-imports, --in-place]
- repo: https://github.com/nbQA-dev/nbQA # for jupyter notebooks
  rev: 1.9.1
  hooks:
    - id: nbqa-isort
      additional_dependencies: [setuptools, isort==5.12.0]
    # Note: autoflake is not officially supported; see Developers.md
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 1.1.0
  hooks:
    - id: sync_with_poetry
      args: [
          '--all',  # Scan all dependencies in poetry.lock (main and dev)
      ]
