version: 2

jobs:
  underactuated-with-drake-peg-revision:
    docker:
      - image: robotlocomotion/circleci:bionic

    working_directory: ~/underactuated

    steps:
      - checkout

      - run:
          name: test prospective merge instead of PR branch
          command: git rebase master

      - run:
          name: setup
          command: ./scripts/continuous_integration/circle_ci/setup_bionic

      - run: echo 'export PYTHONPATH=/root/underactuated/src:/opt/drake/lib/python3.6/site-packages:${PYTHONPATH}' >> $BASH_ENV

      - run:
          name: build and test
          command: ./scripts/continuous_integration/circle_ci/build_test

  underactuated-with-drake-nightly:
    docker:
      - image: robotlocomotion/circleci:bionic

    working_directory: ~/underactuated

    environment:
      - DRAKE_BINARY_URL: "https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-bionic.tar.gz"

    steps:
      - checkout

      - run:
          name: setup
          command: ./scripts/continuous_integration/circle_ci/setup_bionic

      - run: echo 'export PYTHONPATH=/root/underactuated/src:/opt/drake/lib/python3.6/site-packages:${PYTHONPATH}' >> $BASH_ENV

      - run:
          name: build and test
          command: ./scripts/continuous_integration/circle_ci/build_test

  underactuated-with-drake-nightly-xenial:
    docker:
      - image: robotlocomotion/circleci:xenial

    working_directory: ~/underactuated

    environment:
      - DRAKE_BINARY_URL: "https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-xenial.tar.gz"

    steps:
      - checkout

      - run:
          name: setup
          command: ./scripts/continuous_integration/circle_ci/setup_xenial

      - run: echo 'export PYTHONPATH=/root/underactuated/src:/opt/drake/lib/python2.7/site-packages:${PYTHONPATH}' >> $BASH_ENV

      - run:
          name: build and test
          command: ./scripts/continuous_integration/circle_ci/build_test

workflows:
  version: 2
  pr-workflow:
    jobs:
       - underactuated-with-drake-peg-revision

  nightly-workflow:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only: master
    jobs:
       - underactuated-with-drake-nightly
       - underactuated-with-drake-nightly-xenial
